const EVENT_MESSAGE_CSS = {
  JOIN_ROOM_CSS: 'JOIN_ROOM_CSS',
  LEAVE_ROOM_CSS: 'LEAVE_ROOM_CSS',
  SEND_MESSAGE_CSS: 'SEND_MESSAGE_CSS',
  SEND_MESSAGE_OFFLINE_CSS: 'SEND_MESSAGE_OFFLINE_CSS',
  JOIN_ROOM_OFFLINE_CSS: 'JOIN_ROOM_OFFLINE_CSS',
  LEAVE_ROOM_OFFLINE_CSS: 'LEAVE_ROOM_OFFLINE_CSS',
};

module.exports = EVENT_MESSAGE_CSS;
