const EVENT_NOTIFICATION_CSS = {
  JOIN_ROOM_NOTIFICATION_CSS: 'JOIN_ROOM_NOTIFICATION_CSS',
  LEAVE_ROOM_NOTIFICATION_CSS: 'LEAVE_ROOM_NOTIFICATION_CSS',
  SEND_NOTIFICATION_CSS: 'SEND_NOTIFICATION_CSS',
};

module.exports = EVENT_NOTIFICATION_CSS;
