const EVENT_VIDEO_CHAT_CSS = {
    JOIN_ROOM_VIDEO_CHAT_CSS: 'JOIN_ROOM_VIDEO_CHAT_CSS',
    LEAVE_ROOM_VIDEO_CHAT_CSS: 'LEAVE_ROOM_VIDEO_CHAT_CSS',
    ACCEPT_CALL_CSS: 'ACCEPT_CALL_CSS',
    END_CALL_CSS: 'END_CALL_CSS',
    TURN_OFF_VIDEO_CHAT_CSS: 'TURN_OFF_VIDEO_CHAT_CSS'
};

module.exports = EVENT_VIDEO_CHAT_CSS;