const EVENT_MESSAGE_SSC = {
  JOIN_ROOM_SSC: 'JOIN_ROOM_SSC',
  LEAVE_ROOM_SSC: 'LEAVE_ROOM_SSC',
  SEND_MESSAGE_SSC: 'SEND_MESSAGE_SSC',
  SEND_MESSAGE_OFFLINE_SSC: 'SEND_MESSAGE_OFFLINE_SSC',
  JOIN_ROOM_OFFLINE_SSC: 'JOIN_ROOM_OFFLINE_SSC',
  LEAVE_ROOM_OFFLINE_SSC: 'LEAVE_ROOM_OFFLINE_SSC',
};

module.exports = EVENT_MESSAGE_SSC;
