const EVENT_VIDEO_CHAT_SSC = {
    JOIN_ROOM_VIDEO_CHAT_SSC: 'JOIN_ROOM_VIDEO_CHAT_SSC',
    LEAVE_ROOM_VIDEO_CHAT_SSC: 'LEAVE_ROOM_VIDEO_CHAT_SSC',
    ACCEPT_CALL_SSC: 'ACCEPT_CALL_SSC',
    END_CALL_SSC: 'END_CALL_SSC',
    TURN_OFF_VIDEO_CHAT_SSC: 'TURN_OFF_VIDEO_CHAT_SSC'
};

module.exports = EVENT_VIDEO_CHAT_SSC;